### ISSUE TITLE
Hex package failing to build

### ISSUE THREAD

**Issue by sebastiw** [inaka/Emysql#19]
I'm having problems with emysql package on hex.pm. 

When adding
`{emysql, "0.5.0", {pkg, inaka_emysql}}` 
as dependency I cannot build the project, because of missing support directory (or at least missing file `support/crypto_compat.escript`). 

When instead adding the github path it works 
`{emysql, {git, " https://github.com/inaka/Emysql", {tag, "0.5.0"}}}`

According to @jfacorro via mail:
> Problem is probably when the hex package is being built  the contents of the support directory is left out, even though it is used in the compilation.

**Comment by elbrujohalcon** [comment]
Fixed by #20.
